_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NECK_FEAT: "before"
    NUM_CLASSES: 751

  LOSSES:
    TRI:
      MARGIN: 0.3

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/agw_S50"
