MODEL:
  META_ARCHITECTURE: PCB
  
  PCB:
    PART_NUM: 3
    PART_DIM: 512
    EMBEDDING_DIM: 2048
    
    HEAD:
      FULL_DIM: 2048
      PART_DIM: 512
      EMBEDDING_DIM: 512
  
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 101x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 512
    PRETRAIN: True
    WITH_IBN: True
    WITH_SE: True

  HEADS:
    NAME: PcbHead
    WITH_BNNECK: False
    EMBEDDING_DIM: 128
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("CrossEntropyLoss",)
    
    CONTRASTIVE:
      MARGIN: 2.0
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [480, 320]
  SIZE_TEST: [480, 320]

  FLIP:
    ENABLED: True

  CJ:
    ENABLED: True

  AUTOAUG:
    ENABLED: True
    PROB: 0.5
  
  AUGMIX:
    ENABLED: True
    PROB: 0.5

  REA:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 20

SOLVER:
  MAX_EPOCH: 300
  AMP:
    ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.01
  MOMENTUM: 0.95
  NESTEROV: True

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 96

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 100

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 128

DATASETS:
  NAMES: ("ShoeDataset",)
  TESTS: ("ShoeDataset", "OnlineDataset")

OUTPUT_DIR: projects/FastShoe/logs/base-pair

