_BASE_: base.yaml

MODEL:
  META_ARCHITECTURE: PCB
  
  PCB:
    PART_NUM: 3
    PART_DIM: 512
    EMBEDDING_DIM: 2048
    
    HEAD:
      FULL_DIM: 2048
      PART_DIM: 512
      EMBEDDING_DIM: 512
  
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 101x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 512
    PRETRAIN: True
    WITH_IBN: True
    WITH_SE: True

  HEADS:
    NAME: PcbHead
    WITH_BNNECK: False
    EMBEDDING_DIM: 128
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("CrossEntropyLoss",)
    
    CONTRASTIVE:
      MARGIN: 2.0
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [310, 300]
  SIZE_TEST: [310, 300]

  CROP:
    ENABLED: True
    SIZE: [270, 260]
    SCALE: [0.8, 1.2]
    RATIO: [3./4, 4./3]

DATASETS:
  NAMES: ("ShoeDataset",)
  TESTS: ("ShoeDataset", "OnlineDataset")

OUTPUT_DIR: projects/FastShoe/logs/online-pcb

