_BASE_: base-pair.yaml

MODEL:
  META_ARCHITECTURE: Metric

  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 101x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 512
    PRETRAIN: True
    WITH_IBN: True
    WITH_SE: True

  HEADS:
    NAME: PairHead
    WITH_BNNECK: False
    EMBEDDING_DIM: 0
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("ContrastiveLoss",)
    
    CONTRASTIVE:
      MARGIN: 2.0
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [224, 224]  # no need for resize when training
  SIZE_TEST: [224, 224]

  FLIP:
    ENABLED: True

  CJ:
    ENABLED: True

  AUTOAUG:
    ENABLED: True
    PROB: 0.5
  
  AUGMIX:
    ENABLED: True
    PROB: 0.5

  REA:
    ENABLED: True


DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 1000
  AMP:
    ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.001
  MOMENTUM: 0.9
  NESTEROV: False

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 16

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 100

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 32

DATASETS:
  NAMES: ("ShoeDataset",)
  TESTS: ("ShoeDataset", "OnlineDataset")

OUTPUT_DIR: projects/FastShoe/logs/r101_ibn_se
