_BASE_: r101-se-ibn.yaml

MODEL:
  META_ARCHITECTURE: PCB

  PCB:
    EMBEDDING_DIM: 2048

  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 50x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 512
    PRETRAIN: True
    WITH_IBN: False
    WITH_SE: False

  HEADS:
    NAME: PcbHead
    WITH_BNNECK: False
    EMBEDDING_DIM: 128
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("CrossEntropyLoss",)
    
    CONTRASTIVE:
      MARGIN: 2.0
      SCALE: 1.

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 1000
  AMP:
    ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.001
  MOMENTUM: 0.9
  NESTEROV: False

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 28

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 100

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 2

DATASETS:
  NAMES: ("ShoeDataset",)
  TESTS: ("OnlineDataset",)

OUTPUT_DIR: projects/FastShoe/logs/r101_ibn_se
