INPUT:
  SIZE_TRAIN: [0, 0]  # resize size
  SIZE_TEST: [0, 0]

  CROP: 
    ENABLED: False

  FLIP:
    ENABLED: False

  PADDING:
    ENABLED: False

  CJ:
    ENABLED: False
  
  AFFINE:
    ENABLED: False

  AUTOAUG:
    ENABLED: False
  
  AUGMIX:
    ENABLED: False

  REA:
    ENABLED: False
  
  RPT:
    ENABLED: False


DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 1000
  AMP:
    ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.001
  MOMENTUM: 0.9
  NESTEROV: False

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 16

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 100

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 32
  EVALUATOR: ClasEvaluator
