_BASE_: "../Base-bagtricks.yml"

DATALOADER:
  NAIVE_WAY: False

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    POOL_LAYER: gempool
    NECK_FEAT: "after"
  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

SOLVER:
  BIAS_LR_FACTOR: 1.
  IMS_PER_BATCH: 512

TEST:
  IMS_PER_BATCH: 1024

OUTPUT_DIR: "logs/vehicleid/bagtricks_R50-ibn_4gpu"
