_BASE_: "Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 30671

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("VeRiWild",)

SOLVER:
  IMS_PER_BATCH: 512
  MAX_ITER: 64800
  STEPS: [21600, 48600]
  WARMUP_ITERS: 5400

  LOG_PERIOD: 500
  CHECKPOINT_PERIOD: 21600

TEST:
  EVAL_PERIOD: 5400
  IMS_PER_BATCH: 1024

OUTPUT_DIR: "logs/veriwild/bagtricks"
