_BASE_: "Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 13164

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("VehicleID",)

SOLVER:
  IMS_PER_BATCH: 512
  MAX_ITER: 26400
  STEPS: [8800, 19800]
  WARMUP_ITERS: 2200

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 8800

TEST:
  EVAL_PERIOD: 2200
  IMS_PER_BATCH: 1024

OUTPUT_DIR: "logs/vehicleid/bagtricks"
