MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 50x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 2048
    PRETRAIN: True

  HEADS:
    NAME: ClasHead
    WITH_BNNECK: False
    EMBEDDING_DIM: 0
    POOL_LAYER: FastGlobalAvgPool
    CLS_LAYER: Linear
    NUM_CLASSES: 2

  LOSSES:
    NAME: ("CrossEntropyLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

INPUT:
  SIZE_TEST: [256, 256]

  CROP:
    ENABLED: True
    SIZE: [224, 224]

  FLIP:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: TrainingSampler
  NUM_WORKERS: 8

SOLVER:
  MAX_EPOCH: 100
  AMP:
    ENABLED: True

  OPT: SGD
  SCHED: CosineAnnealingLR

  BASE_LR: 0.003
  MOMENTUM: 0.99
  NESTEROV: True

  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.
  IMS_PER_BATCH: 128

  ETA_MIN_LR: 0.00003

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256

DATASETS:
  NAMES: ("Hymenoptera",)
  TESTS: ("Hymenoptera",)

OUTPUT_DIR: projects/FastClas/logs/baseline