_BASE_: "../Base-bagtricks.yml"

MODEL:
  WEIGHTS: "logs/market1501TOdukemtmc/bagtricks_R50_woREA_384/model_final.pth"
  HEADS:
    NUM_CLASSES: 751

    POOL_LAYER: "gempool"


DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("MSMT17",)



INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  DO_AUTOAUG: True
  REA:
    ENABLED: False
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]

TEST:
  PRECISE_BN:
    ENABLED: False
    DATASET: 'MSMT17'


OUTPUT_DIR: "logs/market1501TOdukemtmc/bagtricks_R50_woREA_384"
