_BASE_: "../Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: '/home/liuxinchen3/zhengjinkai/fast-reid/pretrain_model/resnet50_ibn_a.pth.tar'
  HEADS:
    NUM_CLASSES: 30671

SOLVER:
  IMS_PER_BATCH: 512

  MAX_ITER: 64800
  STEPS: [21600, 48600]
  WARMUP_ITERS: 5400

  LOG_PERIOD: 540
  CHECKPOINT_PERIOD: 21600

TEST:
  EVAL_PERIOD: 5400
  IMS_PER_BATCH: 1024

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SamllVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

OUTPUT_DIR: "logs/veriwild/bagtricks_R50-ibn"
