_BASE_: Base-naic.yml

MODEL:
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 34x
    FEAT_DIM: 512
    WITH_IBN: True

  WEIGHTS: projects/NAIC20/logs/reproduce/r34-tripletx10/model_best.pth

DATASETS:
  TESTS: ("NAIC20_R2A",)

TEST:
  RERANK:
    ENABLED: True
    K1: 20
    K2: 3
    LAMBDA: 0.8

  FLIP:
    ENABLED: True

  SAVE_DISTMAT: True

OUTPUT_DIR: projects/NAIC20/logs/r34_ibn-128x256-submit